config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # 目標関係のルーティング
  namespace :user do
    resources :objectives do
      resources :comments, only:[:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end


  # ユーザー関係のルーティング
  namespace :user do
    resources :users, only:[:index, :show, :edit, :update] do 
      member do
        get :following, :followers
      end
    end
  end
  

  # フォロー関係のルーティング
  resources :relationships, only: [:create, :destroy]
  get 'relationships/index_followings'

  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :objectives, dependent: :destroy
         has_many :comments, dependent: :destroy
        # 画像のための記述
         attachment :profile_image

        #  モデルの関連付け
         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user
         has_many :favorites, dependent: :destroy

        # バリデーションの設定
        validates :name, presence: true
        
        #  フォロー関係のメソッド
         def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
    
    # コメントをDBに保存
    def create
        objective = Objective.find(params[:objective_id])
        comment = Comment.new(comment_params)
        comment.user_id = current_user.id
        comment.objective_id = objective.id
        if comment.save
            redirect_to user_objective_path(objective)
            flash[:notice] = "コメントを投稿しました"
        else
            redirect_to user_objective_path(objective)
            flash[:alert] = "コメントの投稿に失敗しました"
        end
    end

    # コメントを削除
    def destroy
        comment = Comment.find_by(id: params[:id], objective_id: params[:objective_id])
        comment.destroy
        flash[:alert] = "コメントを削除しました"
        redirect_to user_objective_path(comment.objective_id)
    end

    private
        def comment_params
            params.require(:comment).permit(:user_id, :objective_id, :comment)
        end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
    def create
        objective = Objective.find(params[:objective_id])
        favorite = current_user.favorites.new(objective_id: objective.id)
        favorite.save
        redirect_to user_objective_path(objective)
    end
    def destroy
        objective = Objective.find(params[:objective_id])
        favorite = current_user.favorites.find_by(objective_id: objective.id)
        favorite.destroy
        redirect_to user_objective_path(objective)
    end
end

app/controllers/user/objectives_controller.rb
class User::ObjectivesController < ApplicationController
    # 個々のユーザーの目標の一覧を表示
    def index
        @objectives = Objective.where(user_id: current_user)
        @comments = Comment.all
    end

    # 目標の詳細を表示
    def show
        @objective = Objective.find(params[:id])
        @comment = Comment.new(objective_id: @objective.id)
        @comments = Comment.where(objective_id: @objective.id) 
    end

    # 目標投稿画面を表示
    def new
        @objective = Objective.new
    end

    # 目標をDBに保存
    def create
        user = current_user
        @objective = Objective.new(objective_params)
        @objective.user_id = current_user.id
        if @objective.save
            flash[:notice] = "目標を投稿しました"
            redirect_to user_user_path(user)
        else
            render :new
        end
    end

    # 目標の編集画面を表示
    def edit
        @objective = Objective.find(params[:id])
    end

    # 目標を更新する
    def update
        @objective = Objective.find(params[:id])
        if @objective.update(objective_params)
            flash[:notice] = "目標を更新しました"
            redirect_to user_objective_path(@objective)
        else
            render :edit
        end
    end

    # 目標を削除する
    def destroy
        objective = Objective.find(params[:id])
        user = objective.user
        objective.destroy
        flash[:alert] = "目標を削除しました"
        redirect_to user_user_path(user)
    end

    private
        def objective_params
            params.require(:objective).permit(:title, :explain, :user_id, :category_id, :comment_id, :achievement, :tag_list)
        end

end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
    # ユーザー一覧の表示
    def index
        @search = User.ransack(params[:q])
        @results = @search.result.page(params[:page])
    end
    
    # ユーザー詳細の表示
    def show
        @user = User.find(params[:id])
        @q = Objective.ransack(params[:q])
        @objectives = @user.objectives.page(params[:page])

        
        #目標検索のための記述
        @search = Objective.where(user_id: @user).ransack(params[:q])
        @results = @search.result.page(params[:page])
        
        #絞り込みのための記述
        if params[:tag_name]
            @results = Objective.tagged_with("#{params[:tag_name]}").page(params[:page])
        end

        @data = [['2019-06-01',50]]
    end

    # ユーザー情報編集画面の表示
    def edit
        @user = User.find(params[:id])
    end

    # ユーザー情報を更新
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "ユーザー情報を更新しました"
            redirect_to user_user_path
        else
            render :edit
        end
    end

    # フォローしてるユーザーの一覧の表示
    def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end

    # フォローされてるユーザーの一覧の表示
    def followers
        @user  = User.find(params[:id])
        @users = @user.followers
        render 'show_follower'
    end


    private
        def user_params
            params.require(:user).permit(:name, :introduction, :profile_image)
        end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/objectives_helper.rb
module User::ObjectivesHelper
end

app/helpers/user/targets_helper.rb
module User::TargetsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
    
end

app/views/user/users/edit.html.erb
<div class="container">
    <div class="form-group">
        <%= form_for @user, url: user_user_path do |f| %>
        <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
                <div class="error">
                    <%= message %>
                </div>
            <% end %>
        <% end %>
        <div class="mb-4">
            <h4>プロフィール画像を変更</h4>
        </div>
        <div class="mb-4">
            <%= f.attachment_field :profile_image %>
        </div>
        <div class="mb-4">
            <h4>名前を入力</h4>
        </div>
        <div class="mb-4">
            <%= f.text_field :name,class:"form-control" %><br>
        </div>
        <div class="mb-4">
            <h2>自己紹介を入力</h2>
        </div>
        <div class="mb-4">
            <%= f.text_area :introduction,class:"form-control" %><br>
        </div>
        <div class="">    
            <%= f.submit "プロフィールを更新", class: "btn btn-success form-control" %>
        </div>
        <% end %>
    </div>
</div>

app/views/user/users/index.html.erb
<div class="container">   
    <%# 検索フォームの設置 %>

    <%= search_form_for @search,url:user_users_path  do |f| %>
        <div class="form-group">
        <%= f.label :name_cont, "ユーザーの名前で検索してください" %>
        <%= f.text_field :name_cont, class: "form-control" %>
        </div>
        <div class="actions"><%= f.submit "検索する" %></div>
    <% end %>

    <%# 検索の結果の表示 %>

    <h4 class="mt-3">ユーザー一覧</h4>
    <% if @results.any? %>
        <% @results.each do |result| %>
            <div class="mb-5 user-index">
                <%= attachment_image_tag result, :profile_image, :fill, 80, 80, fallback: "no_image.png", size:'80x80',class: "mr-5 user-index-img" %>
            <div class="mr-5 mt-3">
                <%= result.name %>
            </div>
            
            <%# フォロー数、フォロワー数の表示 %>
            <div class="mr-5 mt-3">
                <%= link_to following_user_user_path(result) do %>
                    フォロー数<%= result.followings.count %></td>
                <% end %>
            </div>
            <div class="mr-5 mt-3">
                <%= link_to followers_user_user_path(result) do %>
                    フォロワー数:<%= result.followers.count %>
                <% end %>
            </div>
            <div class="mt-3 ml-5">
                <%= link_to "詳細", user_user_path(result), class: "user-index-a btn btn-success" %>
            </div>
            </div>
    <% end %>
    <% end %>


    
    
    <%= paginate @results %>
</div>

app/views/user/users/show.html.erb
<% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
    </div>
<% end %>


<div class="container">
    <div class="">
        <h1>ユーザー詳細</h1>
    </div>
    <div class="">
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size:'150x150', class: "user-show-img" %>
    </div>
    <div class="">
        <table class="table table-border">
            <tr>
                <th>名前</th>    
                <td><%= @user.name %></td>
            </tr>
            <tr>
                <th>自己紹介</th>
                <td><%= @user.introduction %></td>
            </tr>

            <tr>
                <th>フォロー数</th>
                <td><%= link_to following_user_user_path(@user) do %>
                    <%= @user.followings.count %>
                <% end %></td>
            </tr>
            <tr>
            <th>フォロワー数</th>
                <td><%= link_to followers_user_user_path(@user) do %>
                    <%= @user.followers.count %>
                <% end %></td>
            </tr>
        <% unless current_user == @user %>
        <% if current_user.following?(@user) %>
            <%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
            <%= hidden_field_tag :follow_id, @user.id %>
            <tr>
                <td><%= f.submit 'フォローを外す', class: "btn btn-danger" %></td>
            </tr>
            <% end %>
        <% else %>
            <%= form_for(current_user.relationships.build) do |f| %>
            <%= hidden_field_tag :follow_id, @user.id %>
            <tr>
                <td><%= f.submit 'フォローする', class: "btn btn-success" %></td>
            </tr>
            <% end %>
        <% end %>
        <% end %>
        <td>※フォローボタンが効かない場合は一度更新してください</td>
        </div>
        <tr>
            <% if @user == current_user %>
                <td><%= link_to "編集する", edit_user_user_path,class:"btn btn-success" %></td>
            <% end %>
        </tr>
        </table>
    </div>
   
    <div class="mb-4 mt-3">
        <h4 class="index"><%= @user.name %>さんの目標一覧</h4>
    </div>
    <div class="sort">
        <tr>
            <th>並び替え</th>
            <th><%= sort_link(@q, :title, "タイトル") %></th>
            <th><%= sort_link(@q, :achievement, "達成度") %></th>
            <th colspan="3"></th>
        </tr>
    </div>
    <%# 絞り込み解除のための記述　%>
    <%= link_to "絞り込みを解除する",user_user_path(@user), class:"tag btn btn-danger mb-5" %>

    <%# 検索窓の設置 %>
    <%= search_form_for @search,url:user_user_path(@user)  do |f| %>
        <div class="form-group">
            <%= f.label :title_cont, "目標のタイトルで検索してください" %>
            <%= f.text_field :title_cont, class: "form-control" %>
        </div>
        <div class="actions"><%= f.submit "検索する" %></div>
    <% end %>

    
    <h4 class="mt-3">目標一覧</h4>
    <% if @results.any? %>
        <% @results.each do |result| %>
            
                <div class="target">
                    <div class="mb-4">
                        <h4>目標</h4>
                    </div>
                    <div class="mb-4">
                        ・<%= result.title %>
                    </div>
                    <div class="mb-4">
                        <h4>意気込み</h4>
                    </div>
                    <div class="mb-4">
                        ・<%= result.explain %>
                    </div>
                    <div class="mb-4">
                        <%= column_chart [["達成度",result.achievement]], min: 0, max: 100,  colors: ["pink", "#999"], class:"graph" %>
                    </div>
                    <div class="mb-4">
                        <h3>達成度</h3>
                    </div>
                    <div class="mb-4">
                        ・<%= result.achievement %>%
                    </div>
                    <div class="mb-4">
                        <h3>カテゴリー</h3>
                    </div>
                    <div class="mb-4">
                        <% result.tag_list.each do |tag| %>
                        ・<%= link_to tag, user_user_path(tag_name: tag) %>
                        <% end %>
                    </div>
                    <div class="mb-4">
                        <h3>投稿者</h3>
                    </div>
                    <div class="mb-4">
                        <%= result.user.name %>
                    </div>
                        <%= link_to "詳細", user_objective_path(result),class: "btn btn-success" %>
                </div>
            
        <% end %>
    <% end %>
    <%= paginate @results %>
</div>

app/views/user/users/show_follow.html.erb
<div class="container">
    <h3>フォローしてる人一覧</h3>
    <% @user.followings.each do |user| %>
        <div class="follow-index">
            <table class="table table-bordered">
            <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 70, 70, fallback: "no_image.png") %></td>
            <td>  <%= user.name %> </td>
            <td>フォロー数:<%= user.followers.count %></td>
            <td>フォロワー数<%= @user.followings.count %></td>
            <td>
                <% unless current_user == user %>
                    <% if current_user.following?(user) %>
                        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                        <%= hidden_field_tag :follow_id, user.id %>
                        <%= f.submit 'フォローを外す',class:"btn btn-danger" %>
                    <% end %>
                    <% else %>
                        <%= form_for(current_user.relationships.build) do |f| %>
                        <%= hidden_field_tag :follow_id, user.id %>
                        <%= f.submit 'フォローする',class:"btn btn-success" %>
                    <% end %>
                <% end %>
            <% end %>
            </td>
            </tr>
            </table>
        </div>
        <% end %>
</div>

app/views/user/users/show_follower.html.erb
<div class="container">
  <h3>フォローしてくれてる人一覧</h3>
  <% @user.followers.each do |user| %>
    <div class="follow-index">
      <table class="table table-borderd">
      <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.png") %></td>
      <td><%= user.name%></td>
      <td>フォロー数:<%= @user.followers.count %></td>
      <td>フォロワー数<%= @user.followings.count %></td>
        <td>
          <% unless current_user == user %>
          <% if current_user.following?(user) %>
              <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'フォローを外す', class:"btn btn-danger" %>
          <% end %>
          <% else %>
              <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'フォローする',class:"btn btn-success" %>
          <% end %>
          <% end %>
          <% end %>
      </td>
        <td><%= link_to '詳細', user_user_path(user),class:"btn btn-success" %></td>
      </tr>
      
      </table>
    </div>
      <% end %>
</div>